scrapper:
  cookies_file: cookies.jsonl
  urls: []
  job_ids: []
  login_url: https://www.linkedin.com/login
  max_depth: 2
  filters:
    sort_by: []
    date_posted: []
    experience_level: []
    company: []
    remote: []
    job_type: []
    easy_apply: []
    has_verifications: []
    location: []
    industry: []
    job_function: []
    title: []
    under_100_applicants: []
    in_your_network: []
    fair_chance_employer: []
    benefits: []
    commitments: []
  block_media: true
  